#!/bin/sh

cp -r ../plugin.video.filmpalast /home/sascha/addons/
cd /home/sascha/addons/
python addons_xml_generator.py
zip -r plugin.video.filmpalast.zip plugin.video.filmpalast/

scp addons.xml* pi@rasp-wohn:/var/www/
scp plugin.video.filmpalast.zip pi@rasp-wohn:/var/www/plugin.video.filmpalast/

