#!/bin/sh

cp -r ../plugin.video.serien /home/sascha/addons/
cd /home/sascha/addons/
python addons_xml_generator.py
zip -r plugin.video.serien.zip plugin.video.serien/

scp addons.xml* pi@rasp-wohn:/var/www/
scp plugin.video.serien.zip pi@rasp-wohn:/var/www/plugin.video.serien/

