#!/bin/sh

cp -r ../plugin.video.kkiste /home/sascha/addons/
cd /home/sascha/addons/
python addons_xml_generator.py
zip -r plugin.video.kkiste.zip plugin.video.kkiste/

scp addons.xml* pi@rasp-wohn:/var/www/
scp plugin.video.kkiste.zip pi@rasp-wohn:/var/www/plugin.video.kkiste/

